language: ruby

services:
  - docker

env:
  global:
    - secure: rPwSbwpZkyYPDOZyZYLrXH26J4g9IB/oXGuuaAYwmE1eVlSPU0feLJ5lS2jemIW+vahJuWkNpWQtfI9q++EeAXwvqOqRpnIWxjvvVYMzGftGJYRbkdkN5VFhHCKQvyYUIYeqlBZH6hL0im0+o+kxElv8+dgNXquuZ6cRrfPkcwYbbQ0fH75e2kNx1UkV0Wjyh8s8resi++ldZYA16a8sbGCXJ+COCJk0iu+2Eb8HUkBjKE1rhbayYxJT2Y+7j13MWhG8rc0dxxs2gz70lRC8ukZwoO3JWnabwJrTYAbi7ECOoRakejUBXPRo7Ygezvi72AgeYqA9euzDTYAQyTb9znFjoAdsQtv9PgHYyezf0pQHGtJD4GXNbQ/or5rvMhf8yU+xKHuaQL5pZWCdzxw0mF2cosjKU2bQy0QAPwC5DHU/6Oe2Ce+SA53qv9c3KBmH/I9ZNLdNL1fCmyTRqR9H8NoaUPo4a5+tV2ZseX4i/mbSZuj9JAvkW/E9dumYJeByXNv3IrMQBrcn7vfRKUM9rOr6Pq9+jBw9PSqydx1m1IEIo1lNTG5WWfhFA+mYpYsI3GsjBHHL9pgNpR7IatCdBzaKbmsxzP0Zu1hx0y3Scv6d9DCDdZZ2MSHeQNDiuYbxS6SrCBNKbBlKQsdjoSFz2wK6z0JTyTXNhPpxwsqjvj8=
    - secure: O2TX6EBmYqkbNZopN/5wfpyKYQNQjurp1tx6h833/DAxxgi9jUMwtGZZl+Ov3rUt6oiC1E8hVFOhxH+mrIUni3CYG6Zw8IixY0kfjhfTLoU1jRZw+FyjHiKPJ1WqcAaxr9cTgikFJ3i1Fk9v1CFCDUlnYxop7AKsgK5LDN+B/sMWPKdZm9IlmtS3KJbpfTYz8oiAxtOZ9wdtsfkxltzJO6tySQNhogrM/ivt4AwwqtSlYRbkbS8NQHkWwk2z/M4U/Gc4Hdyo59egTqZHiLtxGuC8lB6nvFdCEr0CLYwzdWFj0EXIGuxj6fMn5Dvklm1bycZ7JPDRZe7V2spI6HwLRg+zrBYoIJAdYaBD6ZvDgFXASwQu1TfZjp9uBmgSDl2VDlOEtTVO0aLbArt9Nytdfl9nrSPFnKL+UWjvytmAFbTl10fDHBH+ErM8ZIOTJG34UnBwj4cBaKpmVKNw9S4K7y/b6ZOMfNbvZgc8d3G2WIhkrV+y7V0g6441cKssjP3plUw39fp8CdUfHXPRnIPJbTJ/FijvaM49iOII2Sox0AH7QLzgsTQ0iXD8MGcKfVB2mnG9PyjlhBNUmOfkm1HmSN+2m66wsgsU1MRDQAiDXF6LkAyDecAnbfCTrPmkDkxIdGYENu6l3nqZmALwZ1kTbFLay/m+S8YDhxOlrYkIKVY=

  matrix:
    - TAG=alpine-3.13-v1
    - TAG=alpine-3.12-v1
    - TAG=alpine-3.10-v1
    - TAG=alpine-3.9.4-v4
    - TAG=alpine-3.9.4-v3
    - TAG=alpine-3.9.4-v2
    - TAG=alpine-3.9.4-v1

before_script:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

script:
  - sh build.sh "${TAG}"

after_script:
  - docker images

deploy:
  provider: script
  script: sh push.sh "${TAG}"
  on:
    tags: true