name: Docker Build

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                platform: [
                    "linux/amd64",
                    "linux/arm64"
                ]
                tag: [
                    alpine-3,
                    alpine-3.9.4-v1,
                    alpine-3.9.4-v2,
                    alpine-3.9.4-v3,
                    alpine-3.9.4-v4,
                    alpine-3.10,
                    alpine-3.12,
                    alpine-3.13,
                    alpine-3.14,
                    alpine-3.15,
                    alpine-3.16,
                    alpine-3.19,
                ]

        name: ${{ matrix.tag }} | ${{ matrix.platform }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            - name: Install Docker buildx
              id: buildx
              uses: crazy-max/ghaction-docker-buildx@v1
              with:
                  version: latest

            -   name: Authenticate Docker Hub
                run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            -   name: Build Docker Image
                run: sh build.sh ${{ matrix.tag }} ${{ matrix.platform }}

            -   name: Show Docker Images
                run: docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}}\t{{.Size}}'
