name: Docker Push

on:
  release:
    types: [published]

jobs:
    push:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                tag: [
                    alpine-3.9.4-v1,
                    alpine-3.9.4-v2,
                    alpine-3.9.4-v3,
                    alpine-3.9.4-v4,
                    alpine-3.10,
                    alpine-3.12,
                    alpine-3.13,
                    alpine-3.14,
                    alpine-3.15,
                    alpine-3.16,
                    alpine-3.19,
                ]

        name: TAG-${{ matrix.tag }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v1

            -   name: Authenticate Docker Hub
                run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            -   name: Build Docker Image
                run: bash build.sh ${{ matrix.tag }}

            -   name: Push Docker Image
                run: bash push.sh ${{ matrix.tag }}

            -   name: Show Docker Images
                run: docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}}\t{{.Size}}'